services:
  api-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: polytalko-api-dev
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polytalko-api-prod
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  polytalko-network:
    driver: bridge