apiVersion: apps/v1
kind: Deployment
metadata:
  name: polytalko-api-kubernetes-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polytalko-api-kubernetes
  template:
    metadata:
      labels:
        app: polytalko-api-kubernetes
    spec:
      containers:
        - name: polytalko-api-container
          image: chaykow/polytalko-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              port: 4000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 4000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: polytalko-api-kubernetes-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: polytalko-api-kubernetes
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002